name: Weekly GCC Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * 6'

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: diazaji/debian:toolchain
    steps:
    - uses: actions/checkout@v4
    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@main
      with:
        key: ccache-gcc-master
        max-size: 4G
    - name: Force safe directory
      run: git config --global --add safe.directory '*'
    - name: Download Resources
      run: ./resources.sh master
    - name: Build & Release
      run: ./build.sh master
